import Head from 'next/head'
import Link from 'next/link'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Document</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="title">
        Dont Read{' '}
        <Link href="sw/jalebi">
          <a>this page!</a>
        </Link>
        dfdnmm
      </h1>
    </div>
  )
}
